FROM openjdk:21
EXPOSE 1113
ADD target/gr-conf-zipkin-client-ms3-0.0.1-SNAPSHOT.jar gr-conf-zipkin-client-ms3-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "gr-conf-zipkin-client-ms3-0.0.1-SNAPSHOT.jar"]